version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y jq rsync openssh-client
      - echo "Fetching private key from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id $SECRET_SSH_KEY_ARN --query SecretString --output text > /tmp/id_rsa
      - chmod 600 /tmp/id_rsa
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  build:
    commands:
      - echo "Deploying to both EC2 instances via SSH..."
      - for HOST in 10.0.2.18 10.0.5.56; do
          echo "Deploying to $HOST";
          rsync -avz -e "ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./ ec2-user@$HOST:/var/www/html/;
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ec2-user@$HOST "sudo systemctl restart nginx php-fpm";
        done
