version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y rsync openssh-clients
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
      - chmod 600 /tmp/id_rsa

  build:
    commands:
      - echo "Deploying via SSH..."
      - rsync -avz -e "ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./ ec2-user@10.0.2.18:/var/www/html/
      - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ec2-user@10.0.2.18 "sudo systemctl restart nginx php-fpm"
