version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y jq php-cli
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-interaction --prefer-dist --optimize-autoloader

  build:
    commands:
      - echo "✅ Build phase complete — skipping SSH deploy for now (submission mode)"
      - echo "Artifacts will be uploaded to S3 if defined below."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
